[package]
name = "noslang_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.4", features=["json", "multipart"]}
scraper = "0.19.0"
tokio = {version="1.38.0", features=["full"]}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
